### ISSUE TITLE
Windows 10 64 bits error

### ISSUE THREAD

**Issue by diego200052** [davidpendergast/grovetender#1]
Hi! I try to run release for Windows 64 bits but I get the following error when tried to run it:

![grovetender-error](https://user-images.githubusercontent.com/13511573/80017393-280d1f00-849a-11ea-8b32-aeb321186e85.png)

**Comment by davidpendergast** [comment]
Sorry about that, it looks like you're missing some dependencies. 

And it looks like requirements.txt was pointing to a version of pygame that pip couldn't install, which is my bad. I've fixed that with e567096267b9306c616600def8c8193a97f79372 and so I think it should be easier to setup now.

I believe you'll need python 3.7 or higher (I'm using 3.7.5). And you'll need to install the requirements if you haven't. They're listed in requirements.txt - it's just PyOpenGL, pygame, and numpy. Can use `pip install -r requirements.txt` to do that. If the issue still persists can you grab the console output that occurs with this error?
